### ISSUE TITLE
Removing unnecessary files

### ISSUE THREAD

**Issue by IGNOR90** [cyberinferno/cabal-online-updater#2]
Do not tell me how you can delete files that are not in the list with a small check

**Comment by cyberinferno** [comment]
Deleting files from players game folder that are not there in the full.ini file is not a good idea!

**Comment by IGNOR90** [comment]
I want to delete files that are not in patch.ini

**Comment by IGNOR90** [comment]
> I want to delete files that are not in patch.ini

Can you please tell me is it possible? @cyberinferno

**Comment by cyberinferno** [comment]
> > I want to delete files that are not in patch.ini
> 
> Can you please tell me is it possible? @cyberinferno

It is not possible currently. You can build it yourself as code is open!

**Comment by IGNOR90** [comment]
it's a pity that this is not possible
